"""
Brain Core Module
=================

Database models, schemas, and utilities.

Exports:
    - Models: Base, Tenant, Repository, Resource, Document, DocChunk, Operation, etc.
    - Schemas: Pydantic validation schemas for all entities
    - DB: Session management, connection handling
"""

from .db import (
    compute_content_hash,
    compute_file_hash,
    get_default_tenant_id,
    get_engine,
    get_or_create_operation,
    get_session,
    get_session_factory,
    init_db,
    mark_operation_failed,
    mark_operation_started,
    mark_operation_success,
    similarity_search_chunks,
)
from .models import (
    AgentRun,
    Artifact,
    ArtifactTypeEnum,
    Base,
    Decision,
    DecisionTypeEnum,
    DocChunk,
    Document,
    DocumentConcept,
    DocumentEntity,
    DocumentSummary,
    DocumentTopic,
    KnowledgeEdge,
    KnowledgeNode,
    KnowledgeTypeEnum,
    NodeKnowledgeTypeEnum,
    Operation,
    OperationStatusEnum,
    # Enums
    OperationTypeEnum,
    Repository,
    Resource,
    ResourceDependency,
    ResourceTypeEnum,
    SecurityLevelEnum,
    ShareScopeEnum,
    Tenant,
)
from .schemas import (
    ArtifactCreate,
    ArtifactResponse,
    DecisionCreate,
    DecisionResponse,
    DocChunkCreate,
    DocChunkResponse,
    DocumentCreate,
    DocumentResponse,
    KnowledgeEdgeCreate,
    KnowledgeEdgeResponse,
    KnowledgeNodeCreate,
    KnowledgeNodeResponse,
    OperationCreate,
    OperationResponse,
    RepositoryCreate,
    RepositoryResponse,
    ResourceCreate,
    ResourceResponse,
    TenantCreate,
    TenantResponse,
)

__all__ = [
    # Models
    "Base",
    "Tenant",
    "Repository",
    "Resource",
    "ResourceDependency",
    "Document",
    "DocChunk",
    "Operation",
    "Artifact",
    "Decision",
    "DocumentSummary",
    "DocumentEntity",
    "DocumentTopic",
    "DocumentConcept",
    "AgentRun",
    "KnowledgeNode",
    "KnowledgeEdge",
    # Enums
    "OperationTypeEnum",
    "OperationStatusEnum",
    "ResourceTypeEnum",
    "KnowledgeTypeEnum",
    "SecurityLevelEnum",
    "ArtifactTypeEnum",
    "DecisionTypeEnum",
    "NodeKnowledgeTypeEnum",
    "ShareScopeEnum",
    # DB utilities
    "get_engine",
    "get_session",
    "get_session_factory",
    "init_db",
    "get_or_create_operation",
    "mark_operation_started",
    "mark_operation_success",
    "mark_operation_failed",
    "compute_content_hash",
    "compute_file_hash",
    "get_default_tenant_id",
    "similarity_search_chunks",
    # Schemas
    "TenantCreate",
    "TenantResponse",
    "RepositoryCreate",
    "RepositoryResponse",
    "ResourceCreate",
    "ResourceResponse",
    "OperationCreate",
    "OperationResponse",
    "DocumentCreate",
    "DocumentResponse",
    "DocChunkCreate",
    "DocChunkResponse",
    "ArtifactCreate",
    "ArtifactResponse",
    "DecisionCreate",
    "DecisionResponse",
    "KnowledgeNodeCreate",
    "KnowledgeNodeResponse",
    "KnowledgeEdgeCreate",
    "KnowledgeEdgeResponse",
]
