"""initial_schema

Revision ID: edec7db70b5d
Revises:
Create Date: 2026-01-06 07:10:03.358592

"""

from collections.abc import Sequence
from uuid import uuid4

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.types import CHAR, JSON, TypeDecorator

# revision identifiers, used by Alembic.
revision: str = "edec7db70b5d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Custom Types Definition for Migration Self-Containment
class GUID(TypeDecorator):
    """Platform-independent GUID type."""

    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(UUID())
        else:
            return dialect.type_descriptor(CHAR(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        elif dialect.name == "postgresql":
            return str(value)
        else:
            if not isinstance(value, str):
                return str(value)
            return value

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        else:
            if not isinstance(value, uuid4().__class__):
                import uuid

                return uuid.UUID(value)
            return value


class JSONList(TypeDecorator):
    impl = JSON
    cache_ok = True

    def process_bind_param(self, value, dialect):
        return value

    def process_result_value(self, value, dialect):
        if value is None:
            return []
        return value


def upgrade() -> None:
    # Enable Extensions
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "_schema_version",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("task_hash", sa.String(length=64), nullable=True),
        sa.Column("iteration", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("solution", sa.JSON(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("tools_used", JSONList(), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("relevance_count", sa.Integer(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consolidated", sa.Boolean(), nullable=True),
        sa.Column("parent_id", GUID(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_run_agent_success", "agent_runs", ["agent_id", "success"], unique=False)
    op.create_index("idx_run_started", "agent_runs", ["started_at"], unique=False)
    op.create_index("idx_run_task_hash", "agent_runs", ["task_hash"], unique=False)
    op.create_index("idx_run_tenant", "agent_runs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_agent_id"), "agent_runs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_success"), "agent_runs", ["success"], unique=False)
    op.create_index(op.f("ix_agent_runs_task_hash"), "agent_runs", ["task_hash"], unique=False)
    op.create_index(op.f("ix_agent_runs_tenant_id"), "agent_runs", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_nodes",
        sa.Column("node_id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column(
            "knowledge_type",
            sa.Enum(
                "SOLUTION",
                "PATTERN",
                "INSIGHT",
                "BEST_PRACTICE",
                "FAILURE",
                "OPTIMIZATION",
                name="nodeknowledgetypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "scope", sa.Enum("PRIVATE", "TEAM", "PUBLIC", name="sharescopeenum"), nullable=True
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", JSONList(), nullable=True),
        sa.Column("problem_domain", sa.String(length=100), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=True),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("shared_with", JSONList(), nullable=True),
        sa.Column("prerequisites", JSONList(), nullable=True),
        sa.Column("related_nodes", JSONList(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_index("idx_knode_domain", "knowledge_nodes", ["problem_domain"], unique=False)
    op.create_index("idx_knode_tenant", "knowledge_nodes", ["tenant_id"], unique=False)
    op.create_index(
        "idx_knode_type_scope", "knowledge_nodes", ["knowledge_type", "scope"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_nodes_agent_id"), "knowledge_nodes", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_nodes_problem_domain"),
        "knowledge_nodes",
        ["problem_domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_nodes_tenant_id"), "knowledge_nodes", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_knowledge_nodes_title"), "knowledge_nodes", ["title"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column(
            "clone_path",
            sa.String(length=1000),
            nullable=True,
            comment="Local clone path if applicable",
        ),
        sa.Column("default_branch", sa.String(length=100), nullable=True),
        sa.Column(
            "last_commit_sha", sa.String(length=64), nullable=True, comment="Latest ingested commit"
        ),
        sa.Column("last_commit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_commit_message", sa.Text(), nullable=True),
        sa.Column("file_count", sa.Integer(), nullable=True),
        sa.Column("total_lines", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("languages", JSONList(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ingest_frequency", sa.String(length=50), nullable=True, comment="manual, daily, weekly"
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", JSONList(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "url", name="uq_tenant_repo_url"),
    )
    op.create_index("idx_repo_name", "repositories", ["name"], unique=False)
    op.create_index("idx_repo_tenant", "repositories", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_repositories_name"), "repositories", ["name"], unique=False)
    op.create_index(op.f("ix_repositories_tenant_id"), "repositories", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_edges",
        sa.Column("edge_id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("from_node_id", GUID(), nullable=False),
        sa.Column("to_node_id", GUID(), nullable=False),
        sa.Column("relationship", sa.String(length=50), nullable=False),
        sa.Column("strength", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["from_node_id"], ["knowledge_nodes.node_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(["to_node_id"], ["knowledge_nodes.node_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("edge_id"),
        sa.UniqueConstraint("from_node_id", "to_node_id", "relationship", name="uq_knowledge_edge"),
    )
    op.create_index("idx_kedge_tenant", "knowledge_edges", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_knowledge_edges_from_node_id"), "knowledge_edges", ["from_node_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_edges_relationship"), "knowledge_edges", ["relationship"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_edges_tenant_id"), "knowledge_edges", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_edges_to_node_id"), "knowledge_edges", ["to_node_id"], unique=False
    )
    op.create_table(
        "resources",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("repository_id", GUID(), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_extension", sa.String(length=50), nullable=True),
        sa.Column(
            "resource_type",
            sa.Enum(
                "CODE_FILE",
                "DOCUMENT",
                "IMAGE",
                "CONFIG",
                "DATA",
                "BINARY",
                "DIRECTORY",
                name="resourcetypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "content_hash", sa.String(length=64), nullable=False, comment="SHA-256 of file content"
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("last_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("last_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("has_pii", sa.Boolean(), nullable=True, comment="Contains PII/sensitive data"),
        sa.Column("has_secrets", sa.Boolean(), nullable=True, comment="Contains API keys/secrets"),
        sa.Column(
            "security_flags", JSONList(), nullable=True, comment="Specific security concerns found"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "is_parsed",
            sa.Boolean(),
            nullable=True,
            comment="Whether content has been parsed/chunked",
        ),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "content_hash", name="uq_tenant_content_hash"),
        sa.UniqueConstraint("tenant_id", "repository_id", "file_path", name="uq_tenant_repo_path"),
    )
    op.create_index("idx_resource_language", "resources", ["language"], unique=False)
    op.create_index("idx_resource_repo", "resources", ["repository_id"], unique=False)
    op.create_index("idx_resource_tenant", "resources", ["tenant_id"], unique=False)
    op.create_index("idx_resource_type", "resources", ["resource_type"], unique=False)
    op.create_index(op.f("ix_resources_content_hash"), "resources", ["content_hash"], unique=False)
    op.create_index(
        op.f("ix_resources_file_extension"), "resources", ["file_extension"], unique=False
    )
    op.create_index(op.f("ix_resources_file_name"), "resources", ["file_name"], unique=False)
    op.create_index(op.f("ix_resources_has_pii"), "resources", ["has_pii"], unique=False)
    op.create_index(op.f("ix_resources_has_secrets"), "resources", ["has_secrets"], unique=False)
    op.create_index(op.f("ix_resources_language"), "resources", ["language"], unique=False)
    op.create_index(
        op.f("ix_resources_repository_id"), "resources", ["repository_id"], unique=False
    )
    op.create_index(op.f("ix_resources_tenant_id"), "resources", ["tenant_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("source_resource_id", GUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 for deduplication",
        ),
        sa.Column(
            "doc_type",
            sa.Enum(
                "AGENT_OUTPUT",
                "TASK_RESULT",
                "DATASET",
                "CODE_SNIPPET",
                "DOCUMENTATION",
                "ERROR_SOLUTION",
                "BEST_PRACTICE",
                "RESEARCH_PAPER",
                "CONVERSATION",
                "EXPERIMENT",
                name="knowledgetypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "source", sa.String(length=255), nullable=False, comment="Origin (agent, user, system)"
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "security_level",
            sa.Enum("PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED", name="securitylevelenum"),
            nullable=True,
        ),
        sa.Column("has_pii", sa.Boolean(), nullable=True),
        sa.Column("tags", JSONList(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("parent_id", GUID(), nullable=True),
        sa.Column("is_chunked", sa.Boolean(), nullable=True),
        sa.Column("is_embedded", sa.Boolean(), nullable=True),
        sa.Column("is_analyzed", sa.Boolean(), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(["source_resource_id"], ["resources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "content_hash", name="uq_tenant_doc_hash"),
    )
    op.create_index("idx_doc_created", "documents", ["created_at"], unique=False)
    op.create_index("idx_doc_source", "documents", ["source"], unique=False)
    op.create_index("idx_doc_tenant", "documents", ["tenant_id"], unique=False)
    op.create_index("idx_doc_type", "documents", ["doc_type"], unique=False)
    op.create_index(op.f("ix_documents_category"), "documents", ["category"], unique=False)
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_index(op.f("ix_documents_has_pii"), "documents", ["has_pii"], unique=False)
    op.create_index(op.f("ix_documents_source"), "documents", ["source"], unique=False)
    op.create_index(
        op.f("ix_documents_source_resource_id"), "documents", ["source_resource_id"], unique=False
    )
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_documents_title"), "documents", ["title"], unique=False)
    op.create_table(
        "resource_dependencies",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("source_id", GUID(), nullable=False),
        sa.Column("target_id", GUID(), nullable=False),
        sa.Column(
            "dependency_type",
            sa.String(length=50),
            nullable=False,
            comment="import, include, extends, uses",
        ),
        sa.Column(
            "import_path",
            sa.String(length=500),
            nullable=True,
            comment="The actual import statement",
        ),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["resources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["resources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id", "target_id", "dependency_type", name="uq_resource_dependency"
        ),
    )
    op.create_index("idx_dep_source", "resource_dependencies", ["source_id"], unique=False)
    op.create_index("idx_dep_target", "resource_dependencies", ["target_id"], unique=False)
    op.create_index(
        op.f("ix_resource_dependencies_source_id"),
        "resource_dependencies",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_dependencies_target_id"),
        "resource_dependencies",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_dependencies_tenant_id"),
        "resource_dependencies",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "doc_chunks",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("document_id", GUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "embedding_model",
            sa.String(length=100),
            nullable=True,
            comment="Model used for embedding",
        ),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_doc_chunk_index"),
    )
    op.create_index("idx_chunk_doc", "doc_chunks", ["document_id"], unique=False)
    op.create_index("idx_chunk_tenant", "doc_chunks", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_doc_chunks_document_id"), "doc_chunks", ["document_id"], unique=False)
    op.create_index(op.f("ix_doc_chunks_tenant_id"), "doc_chunks", ["tenant_id"], unique=False)
    op.create_table(
        "document_concepts",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("document_id", GUID(), nullable=False),
        sa.Column("concept", sa.String(length=255), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_concept_doc", "document_concepts", ["document_id"], unique=False)
    op.create_index("idx_concept_relevance", "document_concepts", ["relevance"], unique=False)
    op.create_index("idx_concept_tenant", "document_concepts", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_document_concepts_concept"), "document_concepts", ["concept"], unique=False
    )
    op.create_index(
        op.f("ix_document_concepts_document_id"), "document_concepts", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_concepts_tenant_id"), "document_concepts", ["tenant_id"], unique=False
    )
    op.create_table(
        "document_entities",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("document_id", GUID(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False, comment="PERSON, ORG, GPE, etc."),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("frequency", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_entity_doc", "document_entities", ["document_id"], unique=False)
    op.create_index("idx_entity_label_text", "document_entities", ["label", "text"], unique=False)
    op.create_index("idx_entity_tenant", "document_entities", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_document_entities_document_id"), "document_entities", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_entities_label"), "document_entities", ["label"], unique=False
    )
    op.create_index(
        op.f("ix_document_entities_tenant_id"), "document_entities", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_document_entities_text"), "document_entities", ["text"], unique=False)
    op.create_table(
        "document_summaries",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("document_id", GUID(), nullable=False),
        sa.Column("one_sentence", sa.Text(), nullable=True),
        sa.Column("executive", sa.Text(), nullable=True),
        sa.Column("detailed", sa.Text(), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("generation_params", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", name="uq_doc_summary"),
    )
    op.create_index("idx_summary_tenant", "document_summaries", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_document_summaries_document_id"),
        "document_summaries",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_summaries_tenant_id"), "document_summaries", ["tenant_id"], unique=False
    )
    op.create_table(
        "document_topics",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("document_id", GUID(), nullable=False),
        sa.Column(
            "topic_id", sa.Integer(), nullable=False, comment="Topic cluster ID from BERTopic"
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("keywords", JSONList(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_topic_doc", "document_topics", ["document_id"], unique=False)
    op.create_index("idx_topic_id", "document_topics", ["topic_id"], unique=False)
    op.create_index("idx_topic_tenant", "document_topics", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_document_topics_document_id"), "document_topics", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_topics_tenant_id"), "document_topics", ["tenant_id"], unique=False
    )
    op.create_table(
        "operations",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column(
            "op_type",
            sa.Enum(
                "INGEST_REPO",
                "INGEST_DOCUMENT",
                "CHUNK_DOCUMENT",
                "GENERATE_EMBEDDING",
                "EXTRACT_ENTITIES",
                "EXTRACT_TOPICS",
                "EXTRACT_CONCEPTS",
                "GENERATE_SUMMARY",
                "BUILD_DEPENDENCY_GRAPH",
                "AGENT_TASK",
                "ANALYSIS",
                "RETRIEVAL",
                name="operationtypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "input_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 of normalized inputs",
        ),
        sa.Column("inputs", sa.JSON(), nullable=False, comment="Full input parameters"),
        sa.Column("outputs", sa.JSON(), nullable=True, comment="Operation results/outputs"),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "SUCCESS", "FAILED", "SKIPPED", name="operationstatusenum"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("repository_id", GUID(), nullable=True),
        sa.Column("resource_id", GUID(), nullable=True),
        sa.Column("document_id", GUID(), nullable=True),
        sa.Column(
            "correlation_id",
            sa.String(length=64),
            nullable=True,
            comment="For tracing related operations",
        ),
        sa.Column("parent_operation_id", GUID(), nullable=True),
        sa.Column("agent_id", sa.String(length=100), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["parent_operation_id"],
            ["operations.id"],
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("op_type", "input_hash", name="uq_op_type_input_hash"),
    )
    op.create_index("idx_op_correlation", "operations", ["correlation_id"], unique=False)
    op.create_index("idx_op_created", "operations", ["created_at"], unique=False)
    op.create_index("idx_op_status", "operations", ["status"], unique=False)
    op.create_index("idx_op_tenant", "operations", ["tenant_id"], unique=False)
    op.create_index("idx_op_type_status", "operations", ["op_type", "status"], unique=False)
    op.create_index(op.f("ix_operations_agent_id"), "operations", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_operations_correlation_id"), "operations", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_operations_input_hash"), "operations", ["input_hash"], unique=False)
    op.create_index(op.f("ix_operations_op_type"), "operations", ["op_type"], unique=False)
    op.create_index(op.f("ix_operations_status"), "operations", ["status"], unique=False)
    op.create_index(op.f("ix_operations_tenant_id"), "operations", ["tenant_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("operation_id", GUID(), nullable=False),
        sa.Column(
            "artifact_type",
            sa.Enum(
                "EMBEDDING_INDEX",
                "SUMMARY",
                "ENTITY_LIST",
                "DEPENDENCY_GRAPH",
                "ANALYSIS_REPORT",
                "CODE_ANALYSIS",
                "MODEL_OUTPUT",
                name="artifacttypeenum",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=True, comment="Artifact content if small enough"),
        sa.Column(
            "file_path",
            sa.String(length=1000),
            nullable=True,
            comment="Path to artifact file if stored externally",
        ),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("source_document_id", GUID(), nullable=True),
        sa.Column("source_resource_id", GUID(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True, comment="Quality assessment 0-1"),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["operation_id"], ["operations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_resource_id"], ["resources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_artifact_operation", "artifacts", ["operation_id"], unique=False)
    op.create_index("idx_artifact_tenant", "artifacts", ["tenant_id"], unique=False)
    op.create_index("idx_artifact_type", "artifacts", ["artifact_type"], unique=False)
    op.create_index(
        op.f("ix_artifacts_artifact_type"), "artifacts", ["artifact_type"], unique=False
    )
    op.create_index(op.f("ix_artifacts_operation_id"), "artifacts", ["operation_id"], unique=False)
    op.create_index(op.f("ix_artifacts_tenant_id"), "artifacts", ["tenant_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("operation_id", GUID(), nullable=True),
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column(
            "decision_type",
            sa.Enum(
                "TASK_SELECTION",
                "TOOL_CHOICE",
                "ROUTING",
                "PRIORITIZATION",
                "ESCALATION",
                "RETRY",
                "ABORT",
                name="decisiontypeenum",
            ),
            nullable=False,
        ),
        sa.Column("context", sa.JSON(), nullable=False, comment="Input context for the decision"),
        sa.Column(
            "options_considered", sa.JSON(), nullable=True, comment="List of options evaluated"
        ),
        sa.Column("decision", sa.JSON(), nullable=False, comment="The actual decision made"),
        sa.Column(
            "reasoning", sa.Text(), nullable=True, comment="Explanation of why this decision"
        ),
        sa.Column(
            "confidence", sa.Float(), nullable=True, comment="Confidence in the decision 0-1"
        ),
        sa.Column("outcome", sa.JSON(), nullable=True, comment="Result of the decision"),
        sa.Column("outcome_score", sa.Float(), nullable=True, comment="Quality of outcome 0-1"),
        sa.Column(
            "was_correct",
            sa.Boolean(),
            nullable=True,
            comment="Whether decision was correct in hindsight",
        ),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("outcome_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "decision_latency_ms", sa.Integer(), nullable=True, comment="Time to make decision"
        ),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["operation_id"], ["operations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_decision_agent", "decisions", ["agent_id"], unique=False)
    op.create_index("idx_decision_operation", "decisions", ["operation_id"], unique=False)
    op.create_index("idx_decision_tenant", "decisions", ["tenant_id"], unique=False)
    op.create_index("idx_decision_time", "decisions", ["decided_at"], unique=False)
    op.create_index("idx_decision_type", "decisions", ["decision_type"], unique=False)
    op.create_index(op.f("ix_decisions_agent_id"), "decisions", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_decisions_decision_type"), "decisions", ["decision_type"], unique=False
    )
    op.create_index(op.f("ix_decisions_operation_id"), "decisions", ["operation_id"], unique=False)
    op.create_index(op.f("ix_decisions_tenant_id"), "decisions", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decisions_tenant_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_operation_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_decision_type"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_agent_id"), table_name="decisions")
    op.drop_index("idx_decision_type", table_name="decisions")
    op.drop_index("idx_decision_time", table_name="decisions")
    op.drop_index("idx_decision_tenant", table_name="decisions")
    op.drop_index("idx_decision_operation", table_name="decisions")
    op.drop_index("idx_decision_agent", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_artifacts_tenant_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_operation_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_artifact_type"), table_name="artifacts")
    op.drop_index("idx_artifact_type", table_name="artifacts")
    op.drop_index("idx_artifact_tenant", table_name="artifacts")
    op.drop_index("idx_artifact_operation", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_operations_tenant_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_status"), table_name="operations")
    op.drop_index(op.f("ix_operations_op_type"), table_name="operations")
    op.drop_index(op.f("ix_operations_input_hash"), table_name="operations")
    op.drop_index(op.f("ix_operations_correlation_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_agent_id"), table_name="operations")
    op.drop_index("idx_op_type_status", table_name="operations")
    op.drop_index("idx_op_tenant", table_name="operations")
    op.drop_index("idx_op_status", table_name="operations")
    op.drop_index("idx_op_created", table_name="operations")
    op.drop_index("idx_op_correlation", table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_document_topics_tenant_id"), table_name="document_topics")
    op.drop_index(op.f("ix_document_topics_document_id"), table_name="document_topics")
    op.drop_index("idx_topic_tenant", table_name="document_topics")
    op.drop_index("idx_topic_id", table_name="document_topics")
    op.drop_index("idx_topic_doc", table_name="document_topics")
    op.drop_table("document_topics")
    op.drop_index(op.f("ix_document_summaries_tenant_id"), table_name="document_summaries")
    op.drop_index(op.f("ix_document_summaries_document_id"), table_name="document_summaries")
    op.drop_index("idx_summary_tenant", table_name="document_summaries")
    op.drop_table("document_summaries")
    op.drop_index(op.f("ix_document_entities_text"), table_name="document_entities")
    op.drop_index(op.f("ix_document_entities_tenant_id"), table_name="document_entities")
    op.drop_index(op.f("ix_document_entities_label"), table_name="document_entities")
    op.drop_index(op.f("ix_document_entities_document_id"), table_name="document_entities")
    op.drop_index("idx_entity_tenant", table_name="document_entities")
    op.drop_index("idx_entity_label_text", table_name="document_entities")
    op.drop_index("idx_entity_doc", table_name="document_entities")
    op.drop_table("document_entities")
    op.drop_index(op.f("ix_document_concepts_tenant_id"), table_name="document_concepts")
    op.drop_index(op.f("ix_document_concepts_document_id"), table_name="document_concepts")
    op.drop_index(op.f("ix_document_concepts_concept"), table_name="document_concepts")
    op.drop_index("idx_concept_tenant", table_name="document_concepts")
    op.drop_index("idx_concept_relevance", table_name="document_concepts")
    op.drop_index("idx_concept_doc", table_name="document_concepts")
    op.drop_table("document_concepts")
    op.drop_index(op.f("ix_doc_chunks_tenant_id"), table_name="doc_chunks")
    op.drop_index(op.f("ix_doc_chunks_document_id"), table_name="doc_chunks")
    op.drop_index("idx_chunk_tenant", table_name="doc_chunks")
    op.drop_index("idx_chunk_doc", table_name="doc_chunks")
    op.drop_table("doc_chunks")
    op.drop_index(op.f("ix_resource_dependencies_tenant_id"), table_name="resource_dependencies")
    op.drop_index(op.f("ix_resource_dependencies_target_id"), table_name="resource_dependencies")
    op.drop_index(op.f("ix_resource_dependencies_source_id"), table_name="resource_dependencies")
    op.drop_index("idx_dep_target", table_name="resource_dependencies")
    op.drop_index("idx_dep_source", table_name="resource_dependencies")
    op.drop_table("resource_dependencies")
    op.drop_index(op.f("ix_documents_title"), table_name="documents")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_source_resource_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_source"), table_name="documents")
    op.drop_index(op.f("ix_documents_has_pii"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_index(op.f("ix_documents_category"), table_name="documents")
    op.drop_index("idx_doc_type", table_name="documents")
    op.drop_index("idx_doc_tenant", table_name="documents")
    op.drop_index("idx_doc_source", table_name="documents")
    op.drop_index("idx_doc_created", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_resources_tenant_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_repository_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_language"), table_name="resources")
    op.drop_index(op.f("ix_resources_has_secrets"), table_name="resources")
    op.drop_index(op.f("ix_resources_has_pii"), table_name="resources")
    op.drop_index(op.f("ix_resources_file_name"), table_name="resources")
    op.drop_index(op.f("ix_resources_file_extension"), table_name="resources")
    op.drop_index(op.f("ix_resources_content_hash"), table_name="resources")
    op.drop_index("idx_resource_type", table_name="resources")
    op.drop_index("idx_resource_tenant", table_name="resources")
    op.drop_index("idx_resource_repo", table_name="resources")
    op.drop_index("idx_resource_language", table_name="resources")
    op.drop_table("resources")
    op.drop_index(op.f("ix_knowledge_edges_to_node_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_tenant_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_relationship"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_from_node_id"), table_name="knowledge_edges")
    op.drop_index("idx_kedge_tenant", table_name="knowledge_edges")
    op.drop_table("knowledge_edges")
    op.drop_index(op.f("ix_repositories_tenant_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_name"), table_name="repositories")
    op.drop_index("idx_repo_tenant", table_name="repositories")
    op.drop_index("idx_repo_name", table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_knowledge_nodes_title"), table_name="knowledge_nodes")
    op.drop_index(op.f("ix_knowledge_nodes_tenant_id"), table_name="knowledge_nodes")
    op.drop_index(op.f("ix_knowledge_nodes_problem_domain"), table_name="knowledge_nodes")
    op.drop_index(op.f("ix_knowledge_nodes_agent_id"), table_name="knowledge_nodes")
    op.drop_index("idx_knode_type_scope", table_name="knowledge_nodes")
    op.drop_index("idx_knode_tenant", table_name="knowledge_nodes")
    op.drop_index("idx_knode_domain", table_name="knowledge_nodes")
    op.drop_table("knowledge_nodes")
    op.drop_index(op.f("ix_agent_runs_tenant_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_task_hash"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_success"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent_id"), table_name="agent_runs")
    op.drop_index("idx_run_tenant", table_name="agent_runs")
    op.drop_index("idx_run_task_hash", table_name="agent_runs")
    op.drop_index("idx_run_started", table_name="agent_runs")
    op.drop_index("idx_run_agent_success", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("tenants")
    op.drop_table("_schema_version")
    # ### end Alembic commands ###
